name: flutter_kickstart
description: This is a project that aims to facilitate the start of a new application as well as its maintenance.
version: 1.0.0-beta.8
homepage: https://github.com/michaelopes/flutter_kickstart
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3
  flutter_dotenv: ^5.0.2
  flutter_svg: ^2.0.2
  infinite_scroll_pagination: ^3.2.0
  lottie: ^2.2.0
  shimmer: ^2.0.0
  easy_mask: ^2.0.1
  intl: ^0.18.0
  dio: ^5.0.1
  go_router: ^10.0.0
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
 
